# log = logging.getLogger("bot")
# stream_handler = logging.StreamHandler()
# stream_handler.setLevel(logging.INFO)
# stream_handler.setFormatter(logging.Formatter("%(asctime)s - %(name)s - %(levelname)s - %(message)s", "%b %d %Y %H:%M:%S"))
# log.addHandler(stream_handler)
# file_handler = logging.FileHandler("log_crf/log.txt")
# file_handler.setLevel(logging.DEBUG)
# file_handler.setFormatter(logging.Formatter("%(asctime)s - %(name)s - %(levelname)s - %(message)s", "%b %d %Y %H:%M:%S"))
# log.addHandler(file_handler)
# log.setLevel(logging.DEBUG)